server:
  port: 9090
  application:
    name: spring-mvc-crud

spring:
  main:
    banner-mode: off
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/testdb
    driver-class: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update

logging:
  level:
    root: warn
  org:
    hibernate:
      SQL: trace
      orm:
        jdbc:
          bind: true



